### PR TITLE
[+]: Add support of virtual peernet in dbpservice

### PR DESCRIPTION
**Pull request by AlexiaChen**
-  I Changed some snippet of codes for virtual peer net. please check it again if it is wrong.    @ouyun
- Port dbp service with virtual peer net

### CODE REVIEW

**Comment by ouyun** [comment]
It's OK for me.

**Comment by AlexiaChen** [comment]
> It's OK for me.

@ouyun   OK, Thank you for your check.  :)

**Comment by ouyun** [comment]
@AlexiaChen You are welcome:)

**Comment by AlexiaChen** [comment]
@gc87    This branch can merged into supernode from now :)

**Pull request merged**
