### PR TITLE
Xp dev

### PR DESCRIPTION
**Pull request by xp520**
KB#18#45 About dnseed service 
## DNSeed service process and key points

Core function: provide the initial access node address list for all network nodes

Procedures and key points:

* DNSeed node: node that only provides DNSeed service *

* DNSeed as a new operation mode, the corresponding module is provided with DNSeed service similar through input configuration parameter loading./multiverse DNSeed &*

* the DNSeed service listens on port 6811, and all nodes connected to the DNSeed service are recorded, but connection tests are not done immediately, and untested nodes are stored in memory *

* DNSeed service filters the list once a day. The screening test process is to establish a test connection, obtain the block height of the target node and compare with the local level, and the small difference is considered as the available address entry, otherwise filter

* the node is connected to the DNSeed service, which extracts part of the list of available addresses to send to the new node.(randomly extracts)*

* the address in the list that DNSeed sends out must be tested

* normal nodes will request the list of DNSeed service only if the initial network or if there is no local available node *

* nodes connect to each node individually according to the address list provided by DNSeed service. *

* normal nodes will only add nodes that successfully shake hands to the list and library, and nodes that fail to connect will be removed from the list and library. *

### CODE REVIEW

**Comment by xdwangchn** [comment]
Please resolve conflicts with master branch

**Comment by xp520** [comment]
@xdwangchn Conflict resolved.

**Comment by xdwangchn** [comment]
1. "virtual" is unnecessary int walleve/walleve/peernet/peernet.h
2. put comma at the end of line instead of the begin of the next one 
3. don't insert any dnseed  server code into CMvPeerNet/CMvPeer/CNetwork
4. please keep copyright the same as other files
5. the dynamic dnseed list is unsafe for user' wallet，since any dnseed IP from other node is unverifiable
6.  what difference between MVPROTO_CMD_GETDNSEED/MVPROTO_CMD_DNSEED  and MVPROTO_CMD_GETADDRESS/MVPROTO_CMD_ADDRESS?
7. there is a memory leak issue when create DNSeedService object

**Comment by xp520** [comment]
@xdwangchn After the above problems are fixed and the corresponding functions are implemented, please check whether the merge conditions are met.(some specific details need to be tested to be optimized.)

**Comment by xdwangchn** [comment]
1. don't insert any dnseed server code into CMvPeerNet/CMvPeer/CNetwork
2. please follow the same naming convention，including class name, class member and macro
3. remove unnecessary line and space
4. fix "closed and read" issue
```
network/mvdnseedpeer.cpp

                if(hdrRecv.GetChannel()==MVPROTO_CHN_NETWORK && hdrRecv.GetCommand()==MVPROTO_CMD_ADDRESS)
                {
                    ((CMvPeerNet*)pPeerNet)->HandlePeerClose(this);
                }
                Read(MESSAGE_HEADER_SIZE,boost::bind(&CMvDNSeedPeer::HandleReadHeader,this));
                return true;
```

**Comment by xp520** [comment]
@xdwangchn The above problem has been fixed, please check if there are any other problems.

**Pull request merged**
